redis:
  image: hub.c.163.com/library/redis:3.2.5-alpine
  ports:
    - 6379:6379
  volumes:
    - ./runtime/data/redis:/data
mongodb:
  image: hub.c.163.com/library/mongo:3.2.4
  ports:
    - 27017:27017
  volumes:
    - ./runtime/data/mongodb:/data
mysql:
  image: hub.c.163.com/library/mysql:5.5
  expose:
    - "3306"
  environment:
    - MYSQL_ROOT_PASSWORD=123456
  volumes:
    - ./runtime/data/mysql:/var/lib/mysql
php56:
  image: hub.c.163.com/library/php:5.6-fpm-alpine
  ports:
    - 9000:9000
  links:
    - mysql:mysql
  volumes:
    - ./runtime/www:/www
nginx:
  image: hub.c.163.com/library/nginx:1.11.5-alpine
  ports:
    - 80:80
  links:
    - php56:php-fpm
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./runtime/www:/www
    - ./runtime/var/log/nginx:/var/log/nginx